#from http.client import REQUESTED_RANGE_NOT_SATISFIABLE
from script.constants import PluginPotParameterType
from script.native_parameter_regions import NativeParameterRegions

from util.plain_data import PlainData

__all__ = [
    'PluginParameter',
    'native_plugin_parameters'
]


@PlainData
class PluginParameter:
    index: int
    name: str
    type = PluginPotParameterType.Plugin
    deadzone_centre = None
    deadzone_width = 0.1
    discrete_regions = []


native_plugin_parameters = {
    
    #EXTERNAL PLUGINS:

    # Misc Requested 
     'Sylenth1': [
        PluginParameter(index=42),
        PluginParameter(index=45),
        PluginParameter(index=0),
        PluginParameter(index=2),
        PluginParameter(index=61),
        PluginParameter(index=69),
        PluginParameter(index=70),
        PluginParameter(index=68),
     ],
     'Serum': [
        PluginParameter(index=45),
        PluginParameter(index=46),
        PluginParameter(index=35),
        PluginParameter(index=37),
        PluginParameter(index=218),
        PluginParameter(index=219),
        PluginParameter(index=220),
        PluginParameter(index=221),
     ],
    #-------------------------
    # ALL FREE PLUGINS FROM
    # COMPUTER MUSIC MAGAZINE
    #-------------------------
     'ADM_CM': [
        PluginParameter(index=33),
        PluginParameter(index=34),
        PluginParameter(index=29),
        PluginParameter(index=30),
        PluginParameter(index=35, name="Mangle"),
        PluginParameter(index=27, name="Amount"),
        PluginParameter(index=5, name="Accent Level"),
        PluginParameter(index=32, name="Volume"),
    ],
     'miniBitCM': [
        PluginParameter(index=7),
        PluginParameter(index=8),
        PluginParameter(index=3),
        PluginParameter(index=6),
        PluginParameter(index=12),
        PluginParameter(index=13),
        PluginParameter(index=14),
        PluginParameter(index=5, name="Volume"),
    ],
     'Curve2CM': [
        PluginParameter(index=89),
        PluginParameter(index=90),
        PluginParameter(index=32),
        PluginParameter(index=36),
        PluginParameter(index=59),
        PluginParameter(index=0),
        PluginParameter(index=2),
        PluginParameter(index=4, name="Volume"),
    ],
     'Thorn CM': [
        PluginParameter(index=66),
        PluginParameter(index=67),
        PluginParameter(index=71),
        PluginParameter(index=74),
        PluginParameter(index=30),
        PluginParameter(index=52),
        PluginParameter(index=15),
        PluginParameter(index=0, name="Volume"),
    ],
     'Einklang - CM': [
        PluginParameter(index=7),
        PluginParameter(index=6),
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=4),
        PluginParameter(index=8),
        PluginParameter(index=9),
        PluginParameter(index=10),
    ],
     'Clean Electric Guitar': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3),
        PluginParameter(index=4),
        PluginParameter(index=5),
        PluginParameter(index=6),
        PluginParameter(index=7),
    ],
     'Retro Cazio': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3),
        PluginParameter(index=4),
        PluginParameter(index=5),
        PluginParameter(index=6),
        PluginParameter(index=7),
    ],
      'ZebraCM': [
        PluginParameter(index=98),
        PluginParameter(index=99),
        PluginParameter(index=15),
        PluginParameter(index=20),
        PluginParameter(index=66),
        PluginParameter(index=110),
        PluginParameter(index=117),
        PluginParameter(index=0),
    ], 
    #-------------------------
    # Spitfire
    #-------------------------        
    'BBC Symphony Orchestra': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3), 
        PluginParameter(index=4), 
        PluginParameter(index=5), 
        PluginParameter(index=6), 
        PluginParameter(index=7,), 
    ],
    'Originals - Epic Choir': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=8),
        PluginParameter(index=9),
        PluginParameter(index=10),
        PluginParameter(index=4),
        PluginParameter(index=3),
      ],
      'LABS': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3),
        PluginParameter(index=4),
        PluginParameter(index=20),
        PluginParameter(index=21),
        PluginParameter(index=12),
      ],
    #-------------------------
    # BLEASS: (Free)
    #-------------------------        
      'BLEASS Monolit': [
        PluginParameter(index=62),
        PluginParameter(index=63),
        PluginParameter(index=47),
        PluginParameter(index=50),
        PluginParameter(index=6),
        PluginParameter(index=39),
        PluginParameter(index=43),
        PluginParameter(index=0),
      ],
    #-------------------------
    # : FabFilter
    #-------------------------        
      'One': [
        PluginParameter(index=5),
        PluginParameter(index=6),
        PluginParameter(index=3),
        PluginParameter(index=7),
        PluginParameter(index=10),
        PluginParameter(index=22),
        PluginParameter(index=3),
        PluginParameter(index=24),
      ],
    #-------------------------
    # GForce: 
    #-------------------------        
    'SEM': [
        PluginParameter(index=12),
        PluginParameter(index=13),
        PluginParameter(index=18),
        PluginParameter(index=19),
        PluginParameter(index=66),
        PluginParameter(index=89),
        PluginParameter(index=90),
        PluginParameter(index=87),
      ],      
    'Oddity 2': [
        PluginParameter(index=494),
        PluginParameter(index=509),
        PluginParameter(index=149),
        PluginParameter(index=194),
        PluginParameter(index=69),
        PluginParameter(index=637, name="Delay Amount"),
        PluginParameter(index=682, name="Delay Feedback"),
        PluginParameter(index=600, name="Volume"),
    ],
    #-------------------------
    # Reverb Synth Collection:
    # (Free)
    #-------------------------        
      'PG-8X': [
        PluginParameter(index=20),
        PluginParameter(index=21),
        PluginParameter(index=35),
        PluginParameter(index=38),
        PluginParameter(index=45),
        PluginParameter(index=1,name="Waveform"),
        PluginParameter(index=30,name="Chorus"),
        PluginParameter(index=27),
      ],
      'Crystal': [
        PluginParameter(index=44),
        PluginParameter(index=39),
        PluginParameter(index=45),
        PluginParameter(index=145),
        PluginParameter(index=50),
        PluginParameter(index=475,name="D1 Time"),
        PluginParameter(index=476,name="D1 Feedback"),
        PluginParameter(index=526,name="Voice1 Level"),
      ],
    #-------------------------
    # Softube
    #-------------------------

      'Model 72 Synthesizer System': [
        PluginParameter(index=29),
        PluginParameter(index=30),
        PluginParameter(index=38),
        PluginParameter(index=39),
        PluginParameter(index=6),
        PluginParameter(index=10),
        PluginParameter(index=12),
        PluginParameter(index=41),
      ],

      'Model 84 Polyphonic Synthesizer': [
        PluginParameter(index=10),
        PluginParameter(index=11),
        PluginParameter(index=18),
        PluginParameter(index=21),
        PluginParameter(index=28),
        PluginParameter(index=23),
        PluginParameter(index=22),
        PluginParameter(index=31),
      ],
      
    #-------------------------
    # FLKEY MINI & 37
    # FREE INSTRUMENTS - AAA
    #-------------------------

     'Lounge Lizard Session 4': [
        PluginParameter(index=0, name="Noise"),
        PluginParameter(index=1, name = "Tine Bar"),
        PluginParameter(index=2, name="Tone Amp"), 
        PluginParameter(index=3, name="Symmetry"),
        PluginParameter(index=22, name="Character"),
        PluginParameter(index=4, name="Tremelo Rate"),
        PluginParameter(index=5, name="tremelo Depth"),
        PluginParameter(index=20, name="Level"),
    ],
     'Strum Session 2': [
        PluginParameter(index=0, name="Play Mode"),
        PluginParameter(index=1, name="Clock Rate"),
        PluginParameter(index=2, name="Mod Depth"), 
        PluginParameter(index=3, name="Mod Speed"),
        PluginParameter(index=5, name="Strum Speed"),
        PluginParameter(index=6, name="Strum Velocity"),
        PluginParameter(index=53, name="Reverb"),
        PluginParameter(index=55, name="level"),
    ],        
     'Ultra Analog Session 2': [
        PluginParameter(index=7, name="Frequency"),
        PluginParameter(index=6, name="Resonance"),
        PluginParameter(index=10, name="Attack"), 
        PluginParameter(index=13, name="Release"),
        PluginParameter(index=2, name="Pulse Width"),
        PluginParameter(index=39, name="Effect On/Off"),
        PluginParameter(index=40, name="Effect Type"),
        PluginParameter(index=37, name="Volume"),
    ],
    #-------------------------
    # APPLIED ACOUSTICS
    #-------------------------

     'Ultra Analog VA-3': [
        PluginParameter(index=0),
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3),
        PluginParameter(index=4),
        PluginParameter(index=5),
        PluginParameter(index=6),
        PluginParameter(index=7),
    ],
     
    #-------------------------
    # BEST FREE PLUGINS FROM
    # COMPUTER MUSIC MAGAZINE
    #-------------------------

     'BazilleCM': [
        PluginParameter(index=109),
        PluginParameter(index=115),
        PluginParameter(index=12),
        PluginParameter(index=16),
        PluginParameter(index=45),
        PluginParameter(index=140, name="Center Volume"),
        PluginParameter(index=139, name="Outer Volume"),
        PluginParameter(index=141, name="Feedback"),
    ],
     'Dune': [
        PluginParameter(index=28),
        PluginParameter(index=29),
        PluginParameter(index=18),
        PluginParameter(index=21),
        PluginParameter(index=57, name="Mod Attack"),
        PluginParameter(index=0, name="Osc1 Type"),
        PluginParameter(index=5, name="Osc2 Type"),
        PluginParameter(index=12, name="Osc Mix"),
    ],
     'Fathom': [
        PluginParameter(index=25),
        PluginParameter(index=26),
        PluginParameter(index=27),
        PluginParameter(index=28),
        PluginParameter(index=29),
        PluginParameter(index=30),
        PluginParameter(index=31),
        PluginParameter(index=32),
    ],


    #---------
    # Roland:
    #---------
     'ZENOLOGY': [
        PluginParameter(index=90),
        PluginParameter(index=91),
        PluginParameter(index=92),
        PluginParameter(index=93),
        PluginParameter(index=94),
        PluginParameter(index=166),
        PluginParameter(index=168),
        PluginParameter(index=89),
    ],
    'JUPITER-8': [
        PluginParameter(index=21),
        PluginParameter(index=22),
        PluginParameter(index=30),
        PluginParameter(index=33),
        PluginParameter(index=57),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=999), #TODO
    ],
    'D-50': [
        PluginParameter(index=13),
        PluginParameter(index=14),
        PluginParameter(index=22),
        PluginParameter(index=23),
        PluginParameter(index=11),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=306), 
    ],
    'SH-101': [
        PluginParameter(index=13),
        PluginParameter(index=14),
        PluginParameter(index=16),
        PluginParameter(index=19),
        PluginParameter(index=1),
        PluginParameter(index=26),
        PluginParameter(index=27),
        PluginParameter(index=35), 
    ],
    'SYSTEM-1': [
        PluginParameter(index=29),
        PluginParameter(index=31),
        PluginParameter(index=39),
        PluginParameter(index=42),
        PluginParameter(index=52),
        PluginParameter(index=45),
        PluginParameter(index=46),
        PluginParameter(index=47,name="Delay Time"), #no level?
    ],
    'JUPITER-4': [
        PluginParameter(index=13),
        PluginParameter(index=14),
        PluginParameter(index=22),
        PluginParameter(index=25),
        PluginParameter(index=2),
        PluginParameter(index=51,name="Effect Type"),
        PluginParameter(index=27,name="Effect Depth"),
        PluginParameter(index=37,name="VCA Level"), 
    ],    
    #---------
    # Arturia:
    #---------
     'ARP 2600 V3':
      [
        PluginParameter(index=27),
        PluginParameter(index=26),
        PluginParameter(index=40),
        PluginParameter(index=41),
        PluginParameter(index=83),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=114),
    ],
    'Jup-8 V3': [
        PluginParameter(index=12),
        PluginParameter(index=13),
        PluginParameter(index=25),
        PluginParameter(index=28),
        PluginParameter(index=121),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=204),
    ],
    'CMI V': [
        PluginParameter(index=6),
        PluginParameter(index=7),
        PluginParameter(index=5),
        PluginParameter(index=28),
        PluginParameter(index=121),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=20),
    ],
    'Mini V3': [
        PluginParameter(index=23),
        PluginParameter(index=24),
        PluginParameter(index=26),
        PluginParameter(index=27),
        PluginParameter(index=146),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=0),
    ],
    'Piano V2': [
        PluginParameter(index=77),
        PluginParameter(index=8),
        PluginParameter(index=76),
        PluginParameter(index=12),
        PluginParameter(index=78),
        PluginParameter(index=80),
        PluginParameter(index=36),
        PluginParameter(index=0),
    ],
    'Prophet V3': [
        PluginParameter(index=17),
        PluginParameter(index=19),
        PluginParameter(index=24),
        PluginParameter(index=27),
        PluginParameter(index=178),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=105),
    ],
    'Stage-73 V': [
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
        PluginParameter(index=0),
    ],
    'Analog Lab 4': [
        PluginParameter(index=2),
        PluginParameter(index=4),
        PluginParameter(index=6),
        PluginParameter(index=8),
        PluginParameter(index=102),        
        PluginParameter(index=163),        
        PluginParameter(index=224),        
        PluginParameter(index=000),
    ],
    'Analog Lab V': [
        PluginParameter(index=2),
        PluginParameter(index=4),
        PluginParameter(index=6),
        PluginParameter(index=8),
        PluginParameter(index=102),        
        PluginParameter(index=163),
        PluginParameter(index=224),        
        PluginParameter(index=233),        
    ],
    #---------
    # TAL:
    #---------
    'TAL U-No-LX-V2': [
        PluginParameter(index=10),
        PluginParameter(index=11),
        PluginParameter(index=20),
        PluginParameter(index=23),
        PluginParameter(index=14),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=16, name="Volume"),    ],
    'TAL BassLine 101': [
        PluginParameter(index=26),
        PluginParameter(index=27),
        PluginParameter(index=35),
        PluginParameter(index=38),
        PluginParameter(index=10),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=1, name="Volume"),    ],
    'TAL-J-8': [
        PluginParameter(index=105),
        PluginParameter(index=107),
        PluginParameter(index=65),
        PluginParameter(index=71),
        PluginParameter(index=43),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=0, name="Volume"),    ],
    'TAL Mod': [
        PluginParameter(index=10),
        PluginParameter(index=11),
        PluginParameter(index=74),
        PluginParameter(index=77),
        PluginParameter(index=101),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=0, name="Volume"),    ],
    'U-NO-62 - TAL': [
        PluginParameter(index=12),
        PluginParameter(index=13),
        PluginParameter(index=20),
        PluginParameter(index=23),
        PluginParameter(index=24),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=1, name="Volume"),    ],
    'TAL U-No-LX-V2': [
        PluginParameter(index=10),
        PluginParameter(index=11),
        PluginParameter(index=20),
        PluginParameter(index=23),
        PluginParameter(index=24),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=16, name="Volume"),    ],
     'Generic': [
        PluginParameter(index=90),
        PluginParameter(index=91),
        PluginParameter(index=92),
        PluginParameter(index=93),
        PluginParameter(index=94),
        PluginParameter(index=999),
        PluginParameter(index=999),
        PluginParameter(index=89, name="Volume"),
    ],
    #--------------'
    # Cherry Audio:
    #---------------
     'Elka-X': [
        PluginParameter(index=73),
        PluginParameter(index=74),
        PluginParameter(index=82,name="Upper Attack"),
        PluginParameter(index=85, name="Upper Release"),
        PluginParameter(index=147),
        PluginParameter(index=123),
        PluginParameter(index=130),
        PluginParameter(index=134, name="Volume"),
    ],
     'DCO-106': [
        PluginParameter(index=15),
        PluginParameter(index=16),
        PluginParameter(index=23),
        PluginParameter(index=26),
        PluginParameter(index=0),
        PluginParameter(index=68, name="Delay"),
        PluginParameter(index=70, name="Reverb"),
        PluginParameter(index=29, name="Volume"),
    ],
    'Mercury-4': [
        PluginParameter(index=16),
        PluginParameter(index=18),
        PluginParameter(index=24),
        PluginParameter(index=30),
        PluginParameter(index=64),
        PluginParameter(index=55, name="Echo"),
        PluginParameter(index=58,name="Reverb"),
        PluginParameter(index=32, name="Volume"),
     ],
    'Dreamsynth': [
        PluginParameter(index=100),
        PluginParameter(index=101),
        PluginParameter(index=115),
        PluginParameter(index=118),
        PluginParameter(index=24),
        PluginParameter(index=168,name="Delay"),
        PluginParameter(index=191,name="Reverb"),
        PluginParameter(index=135, name="Volume"),
    ],
    'Minimode': [
        PluginParameter(index=16),
        PluginParameter(index=17),
        PluginParameter(index=22),
        PluginParameter(index=23),
        PluginParameter(index=4),
        PluginParameter(index=1,name="Tune"),
        PluginParameter(index=3,name="Glide Time"),
        PluginParameter(index=25, name="Volume"),
    ],
    'Surrealistic MG-1 Plus': [
        PluginParameter(index=19),
        PluginParameter(index=20),
        PluginParameter(index=22),
        PluginParameter(index=23),
        PluginParameter(index=24),
        PluginParameter(index=25,name="Noise"),
        PluginParameter(index=26,name="Bell"),
        PluginParameter(index=27, name="poly"),
    ],
    'Quadra': [
        PluginParameter(index=53),
        PluginParameter(index=54),
        PluginParameter(index=55),
        PluginParameter(index=58),
        PluginParameter(index=47),
        PluginParameter(index=114,name="Echo"),
        PluginParameter(index=123,name="Reverb"),
        PluginParameter(index=143, name="Tune"),
    ],
    'Lowdown': [
        PluginParameter(index=15),
        PluginParameter(index=11,name="Emphasis"),
        PluginParameter(index=7),
        PluginParameter(index=9),
        PluginParameter(index=6),
        PluginParameter(index=16, name="Presets"),
        PluginParameter(index=20, name="Glide Enable"),
        PluginParameter(index=0, name="Volume"),
    ],
    #==================
    #INTERNAL PLUGINS:
    #==================
    'Sampler': [
        PluginParameter(index=2, name="Filter Cutoff", type=PluginPotParameterType.Channel),
        PluginParameter(index=3, name="Filter Resonance", type=PluginPotParameterType.Channel),
        PluginParameter(index=5, name="Filter Type", type=PluginPotParameterType.Channel,
                        discrete_regions=NativeParameterRegions['Channel_filter_type']),
        PluginParameter(index=13, name="Sample Start", type=PluginPotParameterType.Channel),
        PluginParameter(index=9, name="Gate Time", type=PluginPotParameterType.Channel),
        PluginParameter(index=11, name="Time Shift", type=PluginPotParameterType.Channel),
        PluginParameter(index=12, name="Swing Mix", type=PluginPotParameterType.Channel),
    ],
    'AudioClip': [
        PluginParameter(index=19, name="Filter Cutoff", type=PluginPotParameterType.Channel, deadzone_centre=0.5),
        PluginParameter(index=20, name="Filter Resonance", type=PluginPotParameterType.Channel, deadzone_centre=0.5),
    ],
    'Layer': [
        PluginParameter(index=19, name="Filter Cutoff", type=PluginPotParameterType.Channel, deadzone_centre=0.5),
        PluginParameter(index=20, name="Filter Resonance", type=PluginPotParameterType.Channel, deadzone_centre=0.5),
    ],
    'FL Keys': [
        PluginParameter(index=1, name="Release", deadzone_centre=0.5),
        PluginParameter(index=7, name="Stereo", deadzone_centre=0.5),
        PluginParameter(index=14, name="Overdrive"),
        PluginParameter(index=11, name="Treble", deadzone_centre=0.5),
        PluginParameter(index=5, name="Vel > Muffle"),
        PluginParameter(index=4, name="Muffle"),
        PluginParameter(index=3, name="Vel > Hardness", deadzone_centre=0.5),
        PluginParameter(index=2, name="Hardness", deadzone_centre=0.5),
    ],
    '3x Osc': [
        PluginParameter(index=1, name="Osc 1 Shape",
                        discrete_regions=NativeParameterRegions['3x_Osc_osc_shape']),
        PluginParameter(index=8, name="Osc 2 Shape",
                        discrete_regions=NativeParameterRegions['3x_Osc_osc_shape']),
        PluginParameter(index=15, name="Osc 3 Shape",
                        discrete_regions=NativeParameterRegions['3x_Osc_osc_shape']),
        PluginParameter(index=9, name="Osc 2 Coarse"),
        PluginParameter(index=16, name="Osc 3 Coarse"),
        PluginParameter(index=2, name="Filter Cutoff", type=PluginPotParameterType.Channel),
        PluginParameter(index=3, name="Filter Resonance", type=PluginPotParameterType.Channel),
        PluginParameter(index=5, name="Filter Type", type=PluginPotParameterType.Channel,
                        discrete_regions=NativeParameterRegions['Channel_filter_type']),
    ],
    'FLEX': [
        PluginParameter(index=10),
        PluginParameter(index=11),
        PluginParameter(index=12),
        PluginParameter(index=13),
        PluginParameter(index=14),
        PluginParameter(index=15),
        PluginParameter(index=16),
        PluginParameter(index=17),
    ],
   'Harmless': [
        PluginParameter(index=31, name="Pluck"),
        PluginParameter(index=79, name="Harmonizer Mix"),
        PluginParameter(index=54, name="Filter Frequency"),
        PluginParameter(index=59, name="Filter Resonance"),
        PluginParameter(index=49, name="Filter Decay"),
        PluginParameter(index=52, name="Env > Filter", deadzone_centre=0.5),
        PluginParameter(index=71, name="Phaser Mix"),
        PluginParameter(index=65, name="Unison"),
    ],
    'Harmor': [
        PluginParameter(index=772, name="Modulation X"),
        PluginParameter(index=773, name="Modulation Y"),
        PluginParameter(index=774, name="Modulation Z"),
        PluginParameter(index=75, name="Pluck Decay Time"),
        PluginParameter(index=76, name="Phaser Mix"),
        PluginParameter(index=27, name="Harmonizer Mix"),
        PluginParameter(index=23, name="Harmonic Blur"),
        PluginParameter(index=52, name="Filter Cutoff"),
    ],
    'PoiZone': [
        PluginParameter(index=18, name="Filter Cutoff"),
        PluginParameter(index=19, name="Filter Resonance"),
        PluginParameter(index=23, name="Amp Decay"),
        PluginParameter(index=12, name="Envelope Decay"),
        PluginParameter(index=10, name="Envelope Amount", deadzone_centre=0.5),
        PluginParameter(index=8, name="Osc Balance"),
        PluginParameter(index=38, name="Delay Wet"),
        PluginParameter(index=42, name="Chorus Wet"),
    ],
    'Sytrus': [
        PluginParameter(index=18, name="Modulation X"),
        PluginParameter(index=19, name="Modulation Y"),
        PluginParameter(index=4, name="Volume Decay", deadzone_centre=0.5),
        PluginParameter(index=8, name="Filter Decay", deadzone_centre=0.5),
        PluginParameter(index=11, name="Unison Order"),
        PluginParameter(index=14, name="Unison Pitch"),
        PluginParameter(index=15, name="Unison Sub Level"),
        PluginParameter(index=1, name="Master LFO Level", deadzone_centre=0.5),
    ],
    'GMS': [
        PluginParameter(index=32, name="Filter Cutoff"),
        PluginParameter(index=33, name="Filter Resonance"),
        PluginParameter(index=40, name="Envelope Attack"),
        PluginParameter(index=41, name="Envelope Decay"),
        PluginParameter(index=42, name="Envelope Amount"),
        PluginParameter(index=45, name="LFO Rate"),
        PluginParameter(index=46, name="LFO Amount"),
        PluginParameter(index=65, name="Modulation"),
    ],
    'MiniSynth': [
        PluginParameter(index=8, name="Filter Frequency"),
        PluginParameter(index=9, name="Filter Peak"),
        PluginParameter(index=5, name="Osc Waveform"),
        PluginParameter(index=6, name="Osc Modifier"),
        PluginParameter(index=20, name="LFO Amount", deadzone_centre=0.5),
        PluginParameter(index=19, name="LFO Rate"),
        PluginParameter(index=18, name="LFO Destination"),
        PluginParameter(index=2, name="Slide Time"),
    ],
    'Sawer': [
        PluginParameter(index=27, name="Filter Cutoff"),
        PluginParameter(index=28, name="Filter Resonance"),
        PluginParameter(index=31, name="Filter Mode"),
        PluginParameter(index=45, name="LFO Amount"),
        PluginParameter(index=39, name="LFO Speed"),
        PluginParameter(index=19, name="Sub-Saw Level"),
        PluginParameter(index=18, name="Sub-Saw Harmonic"),
        PluginParameter(index=11, name="Glide Time"),
    ],
    'Transistor Bass': [
        PluginParameter(index=0, name="Tuning", deadzone_centre=0.5),
        PluginParameter(index=41, name="303 Pulse"),
        PluginParameter(index=1, name="Waveform"),
        PluginParameter(index=2, name="Filter Cutoff"),
        PluginParameter(index=4, name="Filter Resonance"),
        PluginParameter(index=5, name="Envelope Mod"),
        PluginParameter(index=6, name="Decay"),
        PluginParameter(index=7, name="Accent"),
    ],
    'MIDI Out': [
        PluginParameter(index=1),
        PluginParameter(index=2),
        PluginParameter(index=3),
        PluginParameter(index=4),
        PluginParameter(index=5),
        PluginParameter(index=6),
        PluginParameter(index=7),
        PluginParameter(index=8),
    ],
    'Morphine': [
        PluginParameter(index=30, name="Master Attack"),
        PluginParameter(index=31, name="Master Decay"),
        PluginParameter(index=32, name="Master Sustain"),
        PluginParameter(index=33, name="Master Release"),
        PluginParameter(index=17, name="Reverb Decay"),
        PluginParameter(index=19, name="Reverb Mix"),
        PluginParameter(index=52, name="Gen A: Pan Range"),
        PluginParameter(index=6, name="Overdrive"),
    ],
    'Ogun': [
        PluginParameter(index=3, name="Modulation X"),
        PluginParameter(index=4, name="Modulation Y"),
        PluginParameter(index=5, name="Timbre Pre-Decay"),
        PluginParameter(index=6, name="Timbre Decay"),
        PluginParameter(index=7, name="Timbre Release"),
        PluginParameter(index=8, name="Timbre Fullness"),
        PluginParameter(index=15, name="Unison Pitch"),
        PluginParameter(index=40, name="EQ Band 1 Level", deadzone_centre=0.5),
    ],
    'Sakura': [
        PluginParameter(index=2, name="Amp Attack"),
        PluginParameter(index=3, name="Amp Decay"),
        PluginParameter(index=4, name="Amp Sustain"),
        PluginParameter(index=5, name="Amp Release"),
        PluginParameter(index=6, name="String 1: Decay"),
        PluginParameter(index=9, name="String 1: Damp"),
        PluginParameter(index=11, name="String 2: Decay"),
        PluginParameter(index=14, name="String 2: Damp"),
    ],
    'ToxicBiohazard': [

        PluginParameter(index=110, name="Osc 2 > 1 FM"),
        PluginParameter(index=44, name="Osc 2 Freq Shift", deadzone_centre=0.5),
        PluginParameter(index=117, name="Osc 3 > 2 FM"),
        PluginParameter(index=45, name="Osc 3 Freq Shift", deadzone_centre=0.5),
        PluginParameter(index=15, name="Filter Cutoff"),
        PluginParameter(index=16, name="Filter Resonance"),
        PluginParameter(index=3, name="Master Attack"),
        PluginParameter(index=1, name="Distortion"),
    ],
    'SimSynth Live': [
        PluginParameter(index=11, name="Filter Cutoff"),
        PluginParameter(index=12, name="Filter Emphasis"),
        PluginParameter(index=15, name="Filter Highpass"),
        PluginParameter(index=16, name="Filter Bandpass"),
        PluginParameter(index=13, name="Env > Filter", deadzone_centre=0.5),
        PluginParameter(index=22, name="Filter Attack"),
        PluginParameter(index=23, name="Filter Decay"),
        PluginParameter(index=18, name="Amp Env Decay"),
    ],
    'DirectWave': [
        PluginParameter(index=32, name="Amp Env Attack"),
        PluginParameter(index=33, name="Amp Env Decay"),
        PluginParameter(index=34, name="Amp Env Sustain"),
        PluginParameter(index=35, name="Amp Env Release"),
        PluginParameter(index=83, name="Delay Send"),
        PluginParameter(index=84, name="Chorus Send"),
        PluginParameter(index=85, name="Reverb Send"),
        PluginParameter(index=1, name="Glide"),
    ],
    'FPC': [
        PluginParameter(index=256, name="Pad 1 Tune", deadzone_centre=0.5),
        PluginParameter(index=257, name="Pad 2 Tune", deadzone_centre=0.5),
        PluginParameter(index=258, name="Pad 3 Tune", deadzone_centre=0.5),
        PluginParameter(index=259, name="Pad 4 Tune", deadzone_centre=0.5),
        PluginParameter(index=260, name="Pad 5 Tune", deadzone_centre=0.5),
        PluginParameter(index=261, name="Pad 6 Tune", deadzone_centre=0.5),
        PluginParameter(index=262, name="Pad 7 Tune", deadzone_centre=0.5),
        PluginParameter(index=263, name="Pad 8 Tune", deadzone_centre=0.5),
    ],
    'Slicex': [
        PluginParameter(index=6, name="Modulation X"),
        PluginParameter(index=7, name="Modulation Y"),
        PluginParameter(index=5, name="Master Pitch", deadzone_centre=0.5),
        PluginParameter(index=8, name="Filter Env"),
        PluginParameter(index=9, name="Filter Cutoff"),
        PluginParameter(index=10, name="Filter Resonance"),
        PluginParameter(index=20, name="Volume Env Decay"),
        PluginParameter(index=28, name="Filter Env Decay"),
    ],
    'Fruity Slicer': [
        PluginParameter(index=2, name="Filter Cutoff", type=PluginPotParameterType.Channel),
        PluginParameter(index=3, name="Filter Resonance", type=PluginPotParameterType.Channel),
        PluginParameter(index=5, name="Filter Type", type=PluginPotParameterType.Channel,
                        discrete_regions=NativeParameterRegions['Channel_filter_type']),
    ],
    'BASSDRUM': [
        PluginParameter(index=6, name="Base"),
        PluginParameter(index=7, name="Peak"),
        PluginParameter(index=8, name="Slide Time"),
        PluginParameter(index=4, name="Drive"),
        PluginParameter(index=15, name="Click Amount"),
        PluginParameter(index=21, name="Noise Mix"),
        PluginParameter(index=17, name="Noise Decay"),
        PluginParameter(index=2, name="Duration"),
    ],
    'Fruity DrumSynth Live': [
        PluginParameter(index=460, name="Osc1 Frequency"),
        PluginParameter(index=461, name="Osc1 Sweep Start"),
        PluginParameter(index=462, name="Osc1 Sweep Time"),
        PluginParameter(index=463, name="Osc1 Env Decay"),
        PluginParameter(index=466, name="Osc2 Frequency"),
        PluginParameter(index=467, name="Osc2 Bandwidth"),
        PluginParameter(index=489, name="O1>O2 Ring Mod"),
        PluginParameter(index=469, name="Osc2 Env Decay"),
    ],
    'Drumaxx': [
        PluginParameter(index=0, name="Ch.1: Volume"),
        PluginParameter(index=44, name="Ch.2: Volume"),
        PluginParameter(index=88, name="Ch.3: Volume"),
        PluginParameter(index=132, name="Ch.4: Volume"),
        PluginParameter(index=176, name="Ch.5: Volume"),
        PluginParameter(index=220, name="Ch.6: Volume"),
        PluginParameter(index=264, name="Ch.7: Volume"),
        PluginParameter(index=308, name="Ch.8: Volume"),
    ],
    'Drumpad': [
        PluginParameter(index=3, name="Mallet Decay"),
        PluginParameter(index=5, name="Mallet Noise RP"),
        PluginParameter(index=6, name="Membrane Decay"),
        PluginParameter(index=8, name="Membrane Tension"),
        PluginParameter(index=12, name="Membrane Shape"),
        PluginParameter(index=13, name="Low Frequency"),
        PluginParameter(index=23, name="Mid Decay"),
        PluginParameter(index=29, name="Pitch", deadzone_centre=0.5),
    ],
    'SoundFont Player': [
        PluginParameter(index=5, name="Env 2 Attack"),
        PluginParameter(index=6, name="Env 2 Decay"),
        PluginParameter(index=7, name="Env 2 Sustain"),
        PluginParameter(index=8, name="Env 2 Release"),
        PluginParameter(index=12, name="Filter Cutoff"),
        PluginParameter(index=4, name="Modulation"),
        PluginParameter(index=2, name="Reverb Send"),
        PluginParameter(index=3, name="Chorus Send"),
    ],
    'Fruity Envelope Controller': [
        PluginParameter(index=88, name="Modulation X"),
        PluginParameter(index=89, name="Modulation Y"),
        PluginParameter(index=0, name="Base Level"),
        PluginParameter(index=1, name="Envelope Level"),
        PluginParameter(index=3, name="Attack Scale", deadzone_centre=0.5),
        PluginParameter(index=4, name="Decay Scale", deadzone_centre=0.5),
        PluginParameter(index=5, name="Sustain Offset", deadzone_centre=0.5),
        PluginParameter(index=6, name="Release Scale", deadzone_centre=0.5),
    ],
    'Fruity Keyboard Controller': [
        PluginParameter(index=0, name="Attack Smoothing"),
        PluginParameter(index=1, name="Release Smoothing"),
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    'Fruit kick': [
        PluginParameter(index=0, name="Max Frequency"),
        PluginParameter(index=1, name="Min Frequency"),
        PluginParameter(index=2, name="Frequency Decay"),
        PluginParameter(index=3, name="Amp Decay"),
        PluginParameter(index=4, name="Click"),
        PluginParameter(index=5, name="Distortion"),
        None,
        None,
    ],
    'BooBass': [
        PluginParameter(index=0, name="Bass"),
        PluginParameter(index=1, name="Mid"),
        PluginParameter(index=2, name="Treble"),
        None,
        None,
        None,
        None,
        None,
    ],
    'Fruity granulizer': [
        PluginParameter(index=0, name="Grain Attack"),
        PluginParameter(index=1, name="Grain Hold"),
        PluginParameter(index=2, name="Grain Spacing", deadzone_centre=0.558),
        PluginParameter(index=3, name="Wave Spacing", deadzone_centre=0.805),
        PluginParameter(index=7, name="Pan"),
        PluginParameter(index=6, name="Randomness"),
        PluginParameter(index=10, name="Sample Start"),
        PluginParameter(index=9, name="Hold Sound"),
    ],
    'PLUCKED!': [
        PluginParameter(index=0, name="Decay"),
        PluginParameter(index=1, name="Color"),
        PluginParameter(index=2, name="Normalize Decay"),
        PluginParameter(index=3, name="Gate"),
        PluginParameter(index=4, name="Widen"),
        None,
        None,
        None,
    ],
    'BeepMap': [
        PluginParameter(index=0, name="Frequency Range"),
        PluginParameter(index=1, name="Pixel Length"),
        PluginParameter(index=2, name="Scale Type"),
        PluginParameter(index=3, name="Use Blue"),
        PluginParameter(index=4, name="Grainy"),
        PluginParameter(index=5, name="Loop"),
        PluginParameter(index=6, name="Widen (Stereo)"),
        None,

    ],
    'Fruity DX10': [
        PluginParameter(index=11, name="Waveform"),
        PluginParameter(index=21, name="Coarse"),
        PluginParameter(index=5, name="Mod 1 Init"),
        PluginParameter(index=6, name="Mod 1 Decay"),
        PluginParameter(index=3, name="Mod 1 Coarse"),
        PluginParameter(index=16, name="Mod 2 Init"),
        PluginParameter(index=17, name="Mod 2 Decay"),
        PluginParameter(index=14, name="Mod 2 Coarse"),
    ],
    'DX10 VSTi': [
        PluginParameter(index=11, name="Waveform"),
        PluginParameter(index=21, name="Coarse"),
        PluginParameter(index=5, name="Mod 1 Init"),
        PluginParameter(index=6, name="Mod 1 Decay"),
        PluginParameter(index=3, name="Mod 1 Coarse"),
        PluginParameter(index=16, name="Mod 2 Init"),
        PluginParameter(index=17, name="Mod 2 Decay"),
        PluginParameter(index=14, name="Mod 2 Coarse"),
    ],    
                                                        'Autogun': [
        PluginParameter(index=0, name="Master Level")
    ]
}
